// ─── PR Creator ─────────────────────────────────────────────────────
// Creates pull requests via the `gh` CLI tool. Generates a PR with the
// task spec, verification results, and judge verdict as context.

import { execFile } from "node:child_process";
import { promisify } from "node:util";

import type { ProjectAdapter } from "../core/adapter-loader.js";
import type { JudgeResult, VerificationResult } from "../core/types.js";
import { getSyncMap } from "../integrations/github/sync-map.js";

const execFileAsync = promisify(execFile);

// ─── Constants ──────────────────────────────────────────────────────

/** Maximum output buffer (1MB) */
const MAX_BUFFER = 1024 * 1024;

/** Timeout for gh commands in milliseconds (60 seconds) */
const GH_TIMEOUT_MS = 60_000;

// ─── Types ──────────────────────────────────────────────────────────

export interface PrCreateResult {
  success: boolean;
  prUrl?: string;
  error?: string;
}

export interface PrCreateInput {
  taskId: string;
  title: string;
  body: string;
  baseBranch: string;
  /** Explicit source branch for host-side/Docker publication. */
  headBranch?: string;
}

// ─── PR body builder ────────────────────────────────────────────────

/**
 * Build a PR body from task context, verification results, and judge verdict.
 */
export function buildPrBody(
  taskId: string,
  taskSpec: string,
  verification: VerificationResult | null,
  judgeResult: JudgeResult,
): string {
  const lines: string[] = [];

  lines.push(`## Task: ${taskId}`);
  lines.push("");

  // Verification summary
  lines.push("## Verification Results");
  if (verification) {
    lines.push(verification.allPassed ? "All checks **PASSED**." : "Some checks **FAILED**.");
    lines.push("");
    for (const cmd of verification.commands) {
      const icon = cmd.passed ? "pass" : "FAIL";
      lines.push(`- [${icon}] **${cmd.name}**: ${cmd.output.slice(0, 200)}`);
    }
    for (const check of verification.conventionChecks) {
      const icon = check.passed ? "pass" : "FAIL";
      lines.push(`- [${icon}] **${check.name}**: ${check.output.slice(0, 200)}`);
    }
  } else {
    lines.push("No verification results available.");
  }
  lines.push("");

  // Judge verdict
  lines.push("## Judge Verdict");
  lines.push(`- **Verdict:** ${judgeResult.verdict}`);
  lines.push(`- **Confidence:** ${(judgeResult.confidence * 100).toFixed(0)}%`);
  if (judgeResult.scopeViolations.length > 0) {
    lines.push(`- **Scope Violations:** ${judgeResult.scopeViolations.join(", ")}`);
  }
  if (judgeResult.criteriaGaps.length > 0) {
    lines.push(`- **Criteria Gaps:** ${judgeResult.criteriaGaps.join(", ")}`);
  }
  if (judgeResult.feedback) {
    lines.push(`- **Feedback:** ${judgeResult.feedback}`);
  }
  lines.push("");

  // Success criteria from task spec (extract as checklist)
  const criteriaMatch = taskSpec.match(/## Success Criteria\s*\n([\s\S]*?)(?=\n##|\n*$)/);
  if (criteriaMatch) {
    lines.push("## Success Criteria");
    lines.push(criteriaMatch[1].trim());
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Quack Agent*");

  return lines.join("\n");
}

/**
 * Build a PR body with GitHub issue link (if mapped).
 */
export async function buildPrBodyWithIssueLink(
  taskId: string,
  taskSpec: string,
  verification: VerificationResult | null,
  judgeResult: JudgeResult,
  adapter: ProjectAdapter,
): Promise<string> {
  let body = buildPrBody(taskId, taskSpec, verification, judgeResult);

  // Check if task is mapped to a GitHub issue
  const githubConfig = adapter.config.integrations?.github;
  if (githubConfig && githubConfig.closeOnMerge) {
    try {
      const syncMap = await getSyncMap(adapter.config);
      const issueNumber = syncMap.getIssueForTask(taskId);
      if (issueNumber) {
        body += `\n\nCloses #${issueNumber}`;
      }
    } catch (err: unknown) {
      // Non-fatal: log but don't block PR creation
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`Failed to check sync map: ${msg}`);
    }
  }

  return body;
}

// ─── PR creation ────────────────────────────────────────────────────

/**
 * Create a pull request using the `gh` CLI.
 *
 * @param input - PR creation parameters (taskId, title, body, baseBranch)
 * @param adapter - The project adapter with project root
 * @returns Result with success status and PR URL
 */
export async function createPullRequest(
  input: PrCreateInput,
  adapter: ProjectAdapter,
): Promise<PrCreateResult> {
  const cwd = adapter.projectRoot;

  try {
    const { stdout, stderr } = await execFileAsync(
      "gh",
      [
        "pr",
        "create",
        "--title",
        input.title,
        "--body",
        input.body,
        "--base",
        input.baseBranch,
        ...(input.headBranch ? ["--head", input.headBranch] : []),
      ],
      {
        cwd,
        timeout: GH_TIMEOUT_MS,
        maxBuffer: MAX_BUFFER,
      },
    );

    // gh pr create outputs the PR URL on stdout
    const prUrl = stdout.trim();
    if (prUrl.startsWith("http")) {
      return { success: true, prUrl };
    }

    // Sometimes the URL is in stderr
    const stderrUrl = stderr.split("\n").find((line) => line.trim().startsWith("http"));
    if (stderrUrl) {
      return { success: true, prUrl: stderrUrl.trim() };
    }

    return {
      success: true,
      prUrl: prUrl || undefined,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    // A remote may accept `gh pr create` and lose the response, or the host
    // may crash before its publication journal is advanced. Recover only an
    // unambiguous PR for the exact host-validated head/base pair.
    if (input.headBranch) {
      try {
        const { stdout } = await execFileAsync(
          "gh",
          [
            "pr",
            "list",
            "--head",
            input.headBranch,
            "--base",
            input.baseBranch,
            "--state",
            "all",
            "--limit",
            "2",
            "--json",
            "url",
          ],
          { cwd, timeout: GH_TIMEOUT_MS, maxBuffer: MAX_BUFFER },
        );
        const parsed = JSON.parse(stdout) as unknown;
        if (
          Array.isArray(parsed) &&
          parsed.length === 1 &&
          typeof parsed[0] === "object" &&
          parsed[0] !== null &&
          "url" in parsed[0] &&
          typeof (parsed[0] as { url?: unknown }).url === "string" &&
          (parsed[0] as { url: string }).url.startsWith("http")
        ) {
          return { success: true, prUrl: (parsed[0] as { url: string }).url };
        }
      } catch {
        // Preserve the original create failure below. Ambiguous or failed
        // lookups are never treated as successful publication.
      }
    }
    return {
      success: false,
      error: `Failed to create PR: ${message}`,
    };
  }
}
