// ─── Task to GitHub Issue Publisher ────────────────────────────────
// Publish a local TASK-*.md to GitHub as a formatted issue.

import * as path from "node:path";

import type { ParsedTask } from "../../core/types.js";
import type { GitHubConfig } from "./github-types.js";
import { parseTaskFile } from "../../core/task-parser.js";
import { listDuplicateClaimants, resolveTaskFile } from "../../core/task-file-resolver.js";
import {
  DuplicateClaimantAdmissionError,
  formatDuplicateClaimantsMessage,
  groupTaskClaimantsByDeclaredId,
} from "../../core/duplicate-claimants.js";
import { runGh } from "./gh-cli.js";

// ─── Issue Body Formatting ──────────────────────────────────────────

/**
 * Build a GitHub issue body from a task spec.
 */
function buildIssueBody(task: ParsedTask, specPath: string): string {
  const lines: string[] = [];

  // Add marker for bidirectional sync
  lines.push(`<!-- quack:task-id=${task.id} -->`);
  lines.push("");

  // Metadata
  lines.push(`## Priority: ${task.priority} | Effort: ${task.effort}`);
  lines.push("");

  // Problem statement
  lines.push("## Problem Statement");
  lines.push(task.problemStatement);
  lines.push("");

  // Current state
  if (task.currentState) {
    lines.push("## Current State");
    lines.push(task.currentState);
    lines.push("");
  }

  // Recommended approach
  if (task.recommendedApproach) {
    lines.push("## Recommended Approach");
    lines.push(task.recommendedApproach);
    lines.push("");
  }

  // Success criteria as checklist
  if (task.successCriteria.length > 0) {
    lines.push("## Success Criteria");
    for (const criterion of task.successCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  // Files to modify
  if (task.filesToModify.length > 0) {
    lines.push("## Files to Modify");
    lines.push("");
    lines.push("| File | Action | Notes |");
    lines.push("|------|--------|-------|");
    for (const file of task.filesToModify) {
      const notes = file.notes.replace(/\|/g, "\\|");
      lines.push(`| \`${file.path}\` | ${file.action} | ${notes} |`);
    }
    lines.push("");
  }

  // Testing requirements
  if (task.testingRequirements.length > 0) {
    lines.push("## Testing Requirements");
    for (const req of task.testingRequirements) {
      lines.push(`- [ ] ${req}`);
    }
    lines.push("");
  }

  // Tags
  if (task.tags.length > 0) {
    lines.push(`**Tags:** ${task.tags.join(", ")}`);
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(
    `*Generated by [Quack Harness](https://github.com/NotADevIAmaMeatPopsicle/Quack-Harness) from \`${specPath}\`*`,
  );
  lines.push("");

  return lines.join("\n");
}

async function publishTaskFile(
  taskIdentity: string,
  taskFile: string,
  task: ParsedTask,
  projectRoot: string,
  config: GitHubConfig,
): Promise<{ issueNumber: number; url: string }> {
  const specPath = path.relative(projectRoot, taskFile).replace(/\\/g, "/");

  const body = buildIssueBody(task, specPath);
  const title = `${task.id}: ${task.title}`;
  const label = config.publishLabel || config.labels?.task || "quack-task";

  try {
    const { stdout } = await runGh(
      [
        "issue",
        "create",
        "--repo",
        `${config.owner}/${config.repo}`,
        "--title",
        title,
        "--label",
        label,
        "--body-file",
        "-",
      ],
      { input: body },
    );

    // gh issue create returns the issue URL
    const url = stdout.trim();
    const match = url.match(/\/issues\/(\d+)$/);
    if (!match) {
      throw new Error(`Failed to parse issue number from URL: ${url}`);
    }

    const issueNumber = parseInt(match[1], 10);
    return { issueNumber, url };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to publish task ${taskIdentity}: ${message}`);
  }
}

// ─── Publish Single Task ────────────────────────────────────────────

/**
 * Publish a task as a GitHub issue.
 */
export async function publishTask(
  taskId: string,
  projectRoot: string,
  config: GitHubConfig,
  taskDir: string = "docs/tasks",
): Promise<{ issueNumber: number; url: string }> {
  const absoluteTaskDir = path.join(projectRoot, taskDir);
  const resolved = await resolveTaskFile(absoluteTaskDir, taskId);
  if (!resolved) {
    throw new Error(`Task file not found for ${taskId}`);
  }
  const task = resolved.task ?? parseTaskFile(resolved.content, resolved.filePath);
  const claimants = await listDuplicateClaimants(absoluteTaskDir, task.id);
  if (claimants.length > 1) {
    throw new DuplicateClaimantAdmissionError({ taskId: task.id, claimants });
  }
  return publishTaskFile(taskId, resolved.filePath, task, projectRoot, config);
}

// ─── Publish All Backlog Tasks ──────────────────────────────────────

/**
 * Publish all BACKLOG tasks to GitHub.
 */
export interface PublishedTaskOutcome {
  taskId: string;
  issueNumber: number;
  url: string;
}

export interface DuplicateClaimantsPublishSkip {
  taskId: string;
  file: string;
  reason: "duplicate_claimants";
  claimants: string[];
  message: string;
}

export interface FailedTaskPublishSkip {
  taskId: string;
  file: string;
  reason: "publish_failed";
  message: string;
}

export type TaskPublishSkip = DuplicateClaimantsPublishSkip | FailedTaskPublishSkip;

export interface PublishAllBacklogOutcome {
  published: PublishedTaskOutcome[];
  skipped: TaskPublishSkip[];
}

const TASK_CLAIMANT_FILE_PATTERN = /^(?:TASK-\d+|SAURUS-REM-\d{3}).*\.md$/;

export async function publishAllBacklog(
  projectRoot: string,
  taskDir: string,
  config: GitHubConfig,
): Promise<PublishAllBacklogOutcome> {
  const { readdir, readFile } = await import("node:fs/promises");
  const tasksPath = path.join(projectRoot, taskDir);
  const entries = await readdir(tasksPath, { withFileTypes: true });

  const candidates: Array<{
    fileName: string;
    filePath: string;
    task: ParsedTask;
  }> = [];
  const skipped: TaskPublishSkip[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (
      (!entry.isFile() && !entry.isSymbolicLink()) ||
      !TASK_CLAIMANT_FILE_PATTERN.test(entry.name)
    ) {
      continue;
    }
    const filePath = path.join(tasksPath, entry.name);
    try {
      const content = await readFile(filePath, "utf-8");
      candidates.push({
        fileName: entry.name,
        filePath,
        task: parseTaskFile(content, filePath),
      });
    } catch (err: unknown) {
      const isPublicationEligible = entry.name.startsWith("TASK-") && entry.name.endsWith(".md");
      if (isPublicationEligible) {
        skipped.push({
          taskId: `unparseable:${entry.name}`,
          file: entry.name,
          reason: "publish_failed",
          message: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }

  const claimantsById = groupTaskClaimantsByDeclaredId(
    candidates.map((candidate) => ({
      fileName: candidate.fileName,
      declaredId: candidate.task.id,
    })),
  );
  const published: PublishedTaskOutcome[] = [];

  for (const candidate of candidates) {
    if (!candidate.fileName.startsWith("TASK-") || !candidate.fileName.endsWith(".md")) {
      continue;
    }

    const legacyTaskId = candidate.fileName.replace(".md", "");

    // Only publish BACKLOG tasks
    if (candidate.task.status !== "BACKLOG") {
      continue;
    }

    const claimants = claimantsById.get(candidate.task.id) ?? [];
    if (claimants.length > 1) {
      const sortedClaimants = [...claimants].sort((a, b) => a.localeCompare(b));
      skipped.push({
        taskId: candidate.task.id,
        file: candidate.fileName,
        reason: "duplicate_claimants",
        claimants: sortedClaimants,
        message: formatDuplicateClaimantsMessage(candidate.task.id, sortedClaimants),
      });
      continue;
    }

    try {
      const result = await publishTaskFile(
        legacyTaskId,
        candidate.filePath,
        candidate.task,
        projectRoot,
        config,
      );
      published.push({ taskId: legacyTaskId, ...result });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      skipped.push({
        taskId: candidate.task.id,
        file: candidate.fileName,
        reason: "publish_failed",
        message: msg,
      });
    }
  }

  return { published, skipped };
}
