// ─── Task to GitHub Issue Publisher ────────────────────────────────
// Publish a local TASK-*.md to GitHub as a formatted issue.

import * as path from "node:path";

import type { ParsedTask } from "../../core/types.js";
import type { GitHubConfig } from "./github-types.js";
import { parseTaskFile } from "../../core/task-parser.js";
import { listDuplicateClaimants, resolveTaskFile } from "../../core/task-file-resolver.js";
import {
  DuplicateClaimantAdmissionError,
  formatDuplicateClaimantsMessage,
  groupTaskClaimantsByDeclaredId,
} from "../../core/duplicate-claimants.js";
import {
  assertIssueNumber,
  assertIssueUrl,
  parseIssueLabels,
  parseJsonObject,
  readBoundGitHubIssuePage,
  runBoundGitHubCommand,
} from "./trusted-github.js";
import { withGitHubPublicationLock } from "./sync-map.js";
import {
  GITHUB_ISSUE_PAGE_SIZE,
  type TrustedGitHubRepository,
} from "../../worker/trusted-executable.js";

const ISSUE_LOOKUP_TIMEOUT_MS = 120_000;
const ISSUE_PAGE_TIMEOUT_MS = 30_000;
const ISSUE_RECOVERY_ATTEMPTS = 3;
const ISSUE_RECOVERY_DELAY_MS = 50;

// ─── Issue Body Formatting ──────────────────────────────────────────

/**
 * Build a GitHub issue body from a task spec.
 */
function buildIssueBody(task: ParsedTask, specPath: string): string {
  const lines: string[] = [];

  // Add marker for bidirectional sync
  lines.push(`<!-- quack:task-id=${task.id} -->`);
  lines.push("");

  // Metadata
  lines.push(`## Priority: ${task.priority} | Effort: ${task.effort}`);
  lines.push("");

  // Problem statement
  lines.push("## Problem Statement");
  lines.push(task.problemStatement);
  lines.push("");

  // Current state
  if (task.currentState) {
    lines.push("## Current State");
    lines.push(task.currentState);
    lines.push("");
  }

  // Recommended approach
  if (task.recommendedApproach) {
    lines.push("## Recommended Approach");
    lines.push(task.recommendedApproach);
    lines.push("");
  }

  // Success criteria as checklist
  if (task.successCriteria.length > 0) {
    lines.push("## Success Criteria");
    for (const criterion of task.successCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  // Files to modify
  if (task.filesToModify.length > 0) {
    lines.push("## Files to Modify");
    lines.push("");
    lines.push("| File | Action | Notes |");
    lines.push("|------|--------|-------|");
    for (const file of task.filesToModify) {
      const notes = file.notes.replace(/\|/g, "\\|");
      lines.push(`| \`${file.path}\` | ${file.action} | ${notes} |`);
    }
    lines.push("");
  }

  // Testing requirements
  if (task.testingRequirements.length > 0) {
    lines.push("## Testing Requirements");
    for (const req of task.testingRequirements) {
      lines.push(`- [ ] ${req}`);
    }
    lines.push("");
  }

  // Tags
  if (task.tags.length > 0) {
    lines.push(`**Tags:** ${task.tags.join(", ")}`);
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(`*Generated by [Quack](https://github.com/quack-ai/quack) from \`${specPath}\`*`);
  lines.push("");

  return lines.join("\n");
}

interface ExpectedPublishedIssue {
  marker: string;
  title: string;
  body: string;
  label: string;
}

interface PublishedIssueIdentity {
  issueNumber: number;
  url: string;
}

interface ParsedPublishedIssue extends PublishedIssueIdentity {
  title: string;
  body: string;
  labels: string[];
  state: "open" | "closed";
  markerCount: number;
}

function normalizeBody(value: string): string {
  return value.replace(/\r\n/gu, "\n");
}

function parsePublishedIssue(
  value: unknown,
  repository: TrustedGitHubRepository,
  description: string,
): ParsedPublishedIssue {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error(`${description} contained an invalid issue`);
  }
  const data = value as Record<string, unknown>;
  if (typeof data.number !== "number") {
    throw new Error(`${description} contained an invalid issue number`);
  }
  const issueNumber = assertIssueNumber(data.number);
  const url = assertIssueUrl(data.url, repository, issueNumber);
  if (typeof data.title !== "string" || typeof data.body !== "string") {
    throw new Error(`${description} contained an invalid title or body`);
  }
  if (typeof data.state !== "string") {
    throw new Error(`${description} contained an invalid state`);
  }
  const state = data.state.toLowerCase();
  if (state !== "open" && state !== "closed") {
    throw new Error(`${description} contained an invalid state`);
  }
  const normalizedBody = normalizeBody(data.body);
  return {
    issueNumber,
    url,
    title: data.title,
    body: normalizedBody,
    labels: parseIssueLabels(data.labels, description),
    state,
    markerCount: (normalizedBody.match(/^<!-- quack:task-id=[^\r\n]+ -->$/gmu) ?? []).length,
  };
}

function markerCount(body: string, marker: string): number {
  return normalizeBody(body)
    .split("\n")
    .filter((line) => line === marker).length;
}

function assertExpectedPublishedIssue(
  issue: ParsedPublishedIssue,
  expected: ExpectedPublishedIssue,
  description: string,
): PublishedIssueIdentity {
  const exactMarkerCount = markerCount(issue.body, expected.marker);
  if (exactMarkerCount !== 1 || issue.markerCount !== 1) {
    throw new Error(`${description} did not contain exactly one expected task marker`);
  }
  if (issue.title !== expected.title) {
    throw new Error(`${description} returned the wrong title`);
  }
  if (issue.body !== normalizeBody(expected.body)) {
    throw new Error(`${description} returned the wrong body`);
  }
  if (!issue.labels.some((label) => label.toLowerCase() === expected.label.toLowerCase())) {
    throw new Error(`${description} did not contain the requested label`);
  }
  if (issue.state !== "open") {
    throw new Error(`${description} did not contain an open issue`);
  }
  return { issueNumber: issue.issueNumber, url: issue.url };
}

async function readExpectedPublishedIssue(
  issueNumber: number,
  expected: ExpectedPublishedIssue,
  projectRoot: string,
  config: GitHubConfig,
): Promise<PublishedIssueIdentity> {
  const readback = await runBoundGitHubCommand(projectRoot, config, [
    "issue",
    "view",
    String(issueNumber),
    "--json",
    "number,url,title,body,labels,state",
  ]);
  return assertExpectedPublishedIssue(
    parsePublishedIssue(
      parseJsonObject(readback.stdout, "GitHub issue publication readback"),
      readback.repository,
      "GitHub issue publication readback",
    ),
    expected,
    "GitHub issue publication readback",
  );
}

async function findExistingPublishedIssue(
  expected: ExpectedPublishedIssue,
  projectRoot: string,
  config: GitHubConfig,
): Promise<PublishedIssueIdentity | undefined> {
  const deadline = Date.now() + ISSUE_LOOKUP_TIMEOUT_MS;
  let after: string | undefined;
  let repositoryIdentity: string | undefined;
  let expectedCount: number | undefined;
  let scannedCount = 0;
  let previousIssueNumber = 0;
  let previousCreatedAt = -Infinity;
  let candidate: number | undefined;

  // Traverse immutable creation order using provider cursors, retaining only
  // one page. Count/progress checks refuse a changing or incomplete collection
  // instead of authorizing a create after a partial marker search.
  do {
    const remainingMs = deadline - Date.now();
    if (remainingMs <= 0)
      throw new Error("GitHub issue publication lookup timed out before completion");
    const lookup = await readBoundGitHubIssuePage(
      projectRoot,
      config,
      after,
      Math.min(ISSUE_PAGE_TIMEOUT_MS, remainingMs),
    );
    const identity =
      `${lookup.repository.host}/${lookup.repository.owner}/${lookup.repository.repo}`.toLowerCase();
    if (repositoryIdentity !== undefined && repositoryIdentity !== identity) {
      throw new Error("GitHub issue publication lookup changed repositories between pages");
    }
    repositoryIdentity = identity;
    const response = parseJsonObject(lookup.stdout, "GitHub issue publication page");
    if (response.errors !== undefined) {
      if (!Array.isArray(response.errors) || response.errors.length > 0) {
        throw new Error("GitHub issue publication page contained GraphQL errors");
      }
    }
    const data = issuePageObject(response.data);
    const repository = issuePageObject(data.repository);
    if (
      typeof repository.nameWithOwner !== "string" ||
      repository.nameWithOwner.toLowerCase() !==
        `${lookup.repository.owner}/${lookup.repository.repo}`.toLowerCase()
    ) {
      throw new Error("GitHub issue publication page returned the wrong repository");
    }
    const connection = issuePageObject(repository.issues);
    const pageInfo = issuePageObject(connection.pageInfo);
    const totalCount = connection.totalCount;
    if (typeof totalCount !== "number" || !Number.isSafeInteger(totalCount) || totalCount < 0) {
      throw new Error("GitHub issue publication page contained an invalid total count");
    }
    expectedCount ??= totalCount;
    if (totalCount !== expectedCount) {
      throw new Error(
        "GitHub issue collection changed during publication lookup; retry the complete lookup",
      );
    }
    if (!Array.isArray(connection.nodes) || connection.nodes.length > GITHUB_ISSUE_PAGE_SIZE) {
      throw new Error("GitHub issue publication page exceeded its bounded page size");
    }
    for (const value of connection.nodes) {
      const issue = issuePageObject(value);
      if (
        typeof issue.number !== "number" ||
        typeof issue.body !== "string" ||
        typeof issue.createdAt !== "string"
      ) {
        throw new Error("GitHub issue publication page contained an invalid issue");
      }
      const issueNumber = assertIssueNumber(issue.number);
      assertIssueUrl(issue.url, lookup.repository, issueNumber);
      const createdAt = Date.parse(issue.createdAt);
      // Transferred issues retain their original creation time while receiving
      // a new destination number. Numbers need not increase in this ordering.
      if (
        !Number.isFinite(createdAt) ||
        createdAt < previousCreatedAt ||
        issueNumber === previousIssueNumber
      ) {
        throw new Error("GitHub issue publication pagination did not advance in creation order");
      }
      previousIssueNumber = issueNumber;
      previousCreatedAt = createdAt;
      scannedCount += 1;
      if (markerCount(issue.body, expected.marker) > 0) {
        if (candidate !== undefined) {
          throw new Error(
            "GitHub issue publication lookup found multiple issues with the task marker",
          );
        }
        candidate = issueNumber;
      }
    }
    if (typeof pageInfo.hasNextPage !== "boolean" || scannedCount > expectedCount) {
      throw new Error("GitHub issue publication page contained inconsistent pagination evidence");
    }
    if (!pageInfo.hasNextPage) {
      if (scannedCount !== expectedCount) {
        throw new Error(
          "GitHub issue publication lookup ended before the complete collection was read",
        );
      }
      break;
    }
    if (
      connection.nodes.length === 0 ||
      scannedCount >= expectedCount ||
      typeof pageInfo.endCursor !== "string" ||
      !pageInfo.endCursor ||
      pageInfo.endCursor.length > 1024 ||
      /[\0\r\n]/u.test(pageInfo.endCursor) ||
      pageInfo.endCursor === after
    ) {
      throw new Error("GitHub issue publication page contained an invalid continuation cursor");
    }
    after = pageInfo.endCursor;
  } while (after !== undefined);

  return candidate === undefined
    ? undefined
    : readExpectedPublishedIssue(candidate, expected, projectRoot, config);
}

function issuePageObject(value: unknown): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new Error("GitHub issue publication page contained an invalid object");
  }
  return value as Record<string, unknown>;
}

async function waitForIssueRecovery(): Promise<void> {
  await new Promise<void>((resolve) => setTimeout(resolve, ISSUE_RECOVERY_DELAY_MS));
}

async function recoverPublishedIssue(
  expected: ExpectedPublishedIssue,
  projectRoot: string,
  config: GitHubConfig,
): Promise<PublishedIssueIdentity | undefined> {
  let lastFailure: string | undefined;
  for (let attempt = 1; attempt <= ISSUE_RECOVERY_ATTEMPTS; attempt += 1) {
    if (attempt > 1) await waitForIssueRecovery();
    try {
      const recovered = await findExistingPublishedIssue(expected, projectRoot, config);
      if (recovered) return recovered;
      lastFailure = undefined;
    } catch (err: unknown) {
      lastFailure = err instanceof Error ? err.message : String(err);
    }
  }
  if (lastFailure) {
    throw new Error(
      `recovery lookup failed after ${ISSUE_RECOVERY_ATTEMPTS} attempts: ${lastFailure}`,
    );
  }
  return undefined;
}

async function publishTaskFile(
  taskIdentity: string,
  taskFile: string,
  task: ParsedTask,
  projectRoot: string,
  config: GitHubConfig,
): Promise<{ issueNumber: number; url: string }> {
  const specPath = path.relative(projectRoot, taskFile).replace(/\\/g, "/");

  const body = buildIssueBody(task, specPath);
  const title = `${task.id}: ${task.title}`;
  const label = config.publishLabel || config.labels?.task || "quack-task";
  const expected: ExpectedPublishedIssue = {
    marker: `<!-- quack:task-id=${task.id} -->`,
    title,
    body,
    label,
  };

  return withGitHubPublicationLock(projectRoot, async () =>
    publishTaskFileWhileLocked(taskIdentity, expected, projectRoot, config),
  );
}

async function publishTaskFileWhileLocked(
  taskIdentity: string,
  expected: ExpectedPublishedIssue,
  projectRoot: string,
  config: GitHubConfig,
): Promise<PublishedIssueIdentity> {
  try {
    const existing = await findExistingPublishedIssue(expected, projectRoot, config);
    if (existing) return existing;
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`Failed to publish task ${taskIdentity}: pre-create lookup failed: ${message}`);
  }

  let createFailure: string;
  try {
    const created = await runBoundGitHubCommand(
      projectRoot,
      config,
      [
        "issue",
        "create",
        `--title=${expected.title}`,
        `--label=${expected.label}`,
        "--body-file",
        "-",
      ],
      { input: expected.body },
    );

    // gh issue create returns the issue URL
    const createUrl = created.stdout.trim();
    const match = /\/issues\/([1-9][0-9]*)\/?$/u.exec(createUrl);
    if (!match) {
      throw new Error(`Failed to parse issue number from URL: ${createUrl}`);
    }

    const issueNumber = Number(match[1]);
    const validatedCreateUrl = assertIssueUrl(createUrl, created.repository, issueNumber);
    const readback = await readExpectedPublishedIssue(issueNumber, expected, projectRoot, config);
    if (readback.url.toLowerCase() !== validatedCreateUrl.toLowerCase()) {
      throw new Error("GitHub issue create response did not match the authoritative readback URL");
    }
    return readback;
  } catch (err: unknown) {
    createFailure = err instanceof Error ? err.message : String(err);
  }

  try {
    const recovered = await recoverPublishedIssue(expected, projectRoot, config);
    if (recovered) return recovered;
  } catch (err: unknown) {
    const recoveryFailure = err instanceof Error ? err.message : String(err);
    throw new Error(
      `Failed to publish task ${taskIdentity}: create outcome was uncertain (${createFailure}); recovery lookup failed: ${recoveryFailure}`,
    );
  }

  throw new Error(
    `Failed to publish task ${taskIdentity}: create outcome was uncertain (${createFailure}); recovery found no uniquely provable issue`,
  );
}

// ─── Publish Single Task ────────────────────────────────────────────

/**
 * Publish a task as a GitHub issue.
 */
export async function publishTask(
  taskId: string,
  projectRoot: string,
  config: GitHubConfig,
  taskDir: string = "docs/tasks",
): Promise<{ issueNumber: number; url: string }> {
  const absoluteTaskDir = path.join(projectRoot, taskDir);
  const resolved = await resolveTaskFile(absoluteTaskDir, taskId);
  if (!resolved) {
    throw new Error(`Task file not found for ${taskId}`);
  }
  const task = resolved.task ?? parseTaskFile(resolved.content, resolved.filePath);
  const claimants = await listDuplicateClaimants(absoluteTaskDir, task.id);
  if (claimants.length > 1) {
    throw new DuplicateClaimantAdmissionError({ taskId: task.id, claimants });
  }
  return publishTaskFile(taskId, resolved.filePath, task, projectRoot, config);
}

// ─── Publish All Backlog Tasks ──────────────────────────────────────

/**
 * Publish all BACKLOG tasks to GitHub.
 */
export interface PublishedTaskOutcome {
  taskId: string;
  issueNumber: number;
  url: string;
}

export interface DuplicateClaimantsPublishSkip {
  taskId: string;
  file: string;
  reason: "duplicate_claimants";
  claimants: string[];
  message: string;
}

export interface FailedTaskPublishSkip {
  taskId: string;
  file: string;
  reason: "publish_failed";
  message: string;
}

export type TaskPublishSkip = DuplicateClaimantsPublishSkip | FailedTaskPublishSkip;

export interface PublishAllBacklogOutcome {
  published: PublishedTaskOutcome[];
  skipped: TaskPublishSkip[];
}

const TASK_CLAIMANT_FILE_PATTERN = /^(?:TASK-\d+|SAURUS-REM-\d{3}).*\.md$/;

export async function publishAllBacklog(
  projectRoot: string,
  taskDir: string,
  config: GitHubConfig,
): Promise<PublishAllBacklogOutcome> {
  const { readdir, readFile } = await import("node:fs/promises");
  const tasksPath = path.join(projectRoot, taskDir);
  const entries = await readdir(tasksPath, { withFileTypes: true });

  const candidates: Array<{
    fileName: string;
    filePath: string;
    task: ParsedTask;
  }> = [];
  const skipped: TaskPublishSkip[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (
      (!entry.isFile() && !entry.isSymbolicLink()) ||
      !TASK_CLAIMANT_FILE_PATTERN.test(entry.name)
    ) {
      continue;
    }
    const filePath = path.join(tasksPath, entry.name);
    try {
      const content = await readFile(filePath, "utf-8");
      candidates.push({
        fileName: entry.name,
        filePath,
        task: parseTaskFile(content, filePath),
      });
    } catch (err: unknown) {
      const isPublicationEligible = entry.name.startsWith("TASK-") && entry.name.endsWith(".md");
      if (isPublicationEligible) {
        skipped.push({
          taskId: `unparseable:${entry.name}`,
          file: entry.name,
          reason: "publish_failed",
          message: err instanceof Error ? err.message : String(err),
        });
      }
    }
  }

  const claimantsById = groupTaskClaimantsByDeclaredId(
    candidates.map((candidate) => ({
      fileName: candidate.fileName,
      declaredId: candidate.task.id,
    })),
  );
  const published: PublishedTaskOutcome[] = [];

  for (const candidate of candidates) {
    if (!candidate.fileName.startsWith("TASK-") || !candidate.fileName.endsWith(".md")) {
      continue;
    }

    const legacyTaskId = candidate.fileName.replace(".md", "");

    // Only publish BACKLOG tasks
    if (candidate.task.status !== "BACKLOG") {
      continue;
    }

    const claimants = claimantsById.get(candidate.task.id) ?? [];
    if (claimants.length > 1) {
      const sortedClaimants = [...claimants].sort((a, b) => a.localeCompare(b));
      skipped.push({
        taskId: candidate.task.id,
        file: candidate.fileName,
        reason: "duplicate_claimants",
        claimants: sortedClaimants,
        message: formatDuplicateClaimantsMessage(candidate.task.id, sortedClaimants),
      });
      continue;
    }

    try {
      const result = await publishTaskFile(
        legacyTaskId,
        candidate.filePath,
        candidate.task,
        projectRoot,
        config,
      );
      published.push({ taskId: candidate.task.id, ...result });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      skipped.push({
        taskId: candidate.task.id,
        file: candidate.fileName,
        reason: "publish_failed",
        message: msg,
      });
    }
  }

  return { published, skipped };
}
